apiVersion: v1
kind: Service
metadata:
  name: learntogrow-backend
  namespace: default
  labels:
    app: learntogrow-backend
spec:
  selector:
    app: learntogrow-backend
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30800
    protocol: TCP
    name: http
  type: NodePort
