apiVersion: v1
kind: Secret
metadata:
  name: learntogrow-secrets
  namespace: default
type: Opaque
stringData:
  db-name: "your-database-name"
  db-user: "your-database-user"
  db-password: "your-database-password"
