apiVersion: v1
kind: Service
metadata:
  name: learntogrow-frontend
  namespace: default
spec:
  selector:
    app: learntogrow-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081
      name: http
  type: NodePort
