apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  config.json: |
    {
      "apiUrl": "http://10.0.0.134:30800/api/v1",
      "appName": "LearnToGrow Dev",
      "environment": "development",
      "features": {
        "enableDebug": true,
        "showDebugInfo": true
      },
      "defaults": {
        "questionType": "multiple_choice",
        "difficulty": 0.5
      }
    }
